<?php
namespace php_active_record;
include_once(dirname(__FILE__) . "/../../config/environment.php");

// /* during development
ini_set('error_reporting', E_ALL);
ini_set('display_errors', true);
$GLOBALS['ENV_DEBUG'] = true; //set to true during development
// */


// $browser = Functions::getBrowser(); // echo "Browser: " . $browser;
// if($browser == 'Firefox') $browser_comment = "Browse...";
// else                      $browser_comment = "Choose File"; //Safari Chrome
$browser_comment = "Choose File"; //Safari Chrome

?>
<table border="1" cellpadding="15" cellspacing="1" align="center" width="40%">
    <tr align="center">
        <td><b>Trait spreadsheet to DwC-A Tool</b>
        <!---
        <small><br><a href='https://eol-jira.bibalex.org/browse/COLLAB-1004?focusedCommentId=64188&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-64188'>(work in progress)</a></small>
        --->
        </td>
    </tr>
    <tr>
        <td>
        <table><tr>
            <td width="70%">
                <font size="3">
                 <ul>
                 <!--- orig static file from github:
                  <li>Download to your computer the input spreadsheet template <a href="https://github.com/eliagbayani/EOL-connector-data-files/raw/master/Trait_Data_Import/Trait_template.xlsx">here</a>.</li>
                  --->
                  <li>Download to your computer the input spreadsheet template <a href="temp/Trait_template.xlsx">here</a>.</li>
                  <li>Open spreadsheet, enter your own data and save.</li>
                  <li>Upload file using [<?php echo $browser_comment ?>] button below.</li>
                </ul>
                </font>
            </td>
            <td>
                <form action="form_result_upload.php" method="post" enctype="multipart/form-data">
                <font size="2">
                    You can also upload an updated spreadsheet template, with an updated vocabulary sheet.<br>
                    Upload template: <input type="file" name="file_upload" id="file_upload" size="100"><br>
                        <input type="submit" value="Submit template">
                        <input type="reset" value="Reset">
                </font>
                </form>
            
            </td>
        </tr></table>
        </td>
    </tr>
    <form action="form_result.php" method="post" enctype="multipart/form-data">
    <!---
    <tr>
        <td>
            <font size="3">Excel File URL: </font><input type="text" name="form_url" size="100">
            <br>
            <small>
                <i>e.g. http://mydomain.org/spreadsheets/Trait_template.xlsx</i>
            </small>
        </td>
    </tr>
    --->
    <tr>
        <td>
            <font size="3">Upload input Excel file: </font><input type="file" name="file_upload" id="file_upload" size="100">
        </td>
    </tr>
    <tr>
        <td>
            <small>(.xlsx or .xls) OR (.xlsx.zip, .xls.zip)</small>
        </td>
    </tr>
    <!---
    Project: a short text string, eg: "KANB"
    Department: a short text string, which we can constrain to a menu of options, eg: "FISH"
    License: a text string, which we can constrain to a menu of options, eg: "CreativeCommons – Attribution Non-Commercial (by-nc)"
    License Year: a four digit number, unless you'd like to constrain it further. (I'm told a range of dates might happen, 1940, etc.)
    License Institution: a text string, which we can constrain to a menu of options, eg: "Smithsonian Institution National Museum of Natural History"
    License Contact: a short text string, eg: "williamsjt@si.edu" . <== optional field
    sample $json value: '{"Proj":"KANB", "Dept":"FISH", "Lic":"CreativeCommons – Attribution Non-Commercial (by-nc)", "Lic_yr":"", "Lic_inst":"", "Lic_cont":""}';
    --->
    <tr>
        <td>
            <table>
            <tr><td>Description:</td> <td><input type='text' name='Short_Desc' size='100' required></td></tr>
            <tr><td></td>
                <td>
                    <small>Please enter a short description of your file.
                    </small>
                </td>
            </tr>
            </table>
        </td>
    </tr>
    <tr>
        <td>
            <table>
            <tr><td>Upload ID:</td> <td><input type='text' name='Filename_ID'></td></tr>
            <tr><td></td>
                <td>
                    <small>Optional. Please enter Upload ID to update a previous upload.<br>
                    Upload ID is generated by the system.<br>
                    If left blank, the system assumes this will be a new upload and will create a new resource in OpenData.eol.org.
                    </small>
                </td>
            </tr>
            </table>
        </td>
    </tr>
    <tr align="center">
        <td>
            <input type="submit" value="Convert Spreadsheet to DwCA">
            <input type="reset" value="Reset">
            <!--- <input type="checkbox" name="validate">Validate --->
        </td>
    </tr>
    </form>
    <tr align="left">
        <td><?php echo "<a href='https://opendata.eol.org/dataset/trait-spreadsheet-repository'>OpenData Resources For Uploaded Spreadsheets</a>"; ?></td>
        <!---
        <td><small><?php echo "<a href='../specimen_export/'>Specimen Export Tool</a> | <a href='../BOLD2iNAT/'>BOLDS-to-iNaturalist Tool</a>"; ?><small></td>
        <td><small><?php echo "<a href='../specimen_export/'>Specimen Export Tool</a>"; ?><small></td>
        --->
    </tr>
</table>
