<?php
namespace php_active_record;
/* originated here: https://eol-jira.bibalex.org/browse/DATA-1820

This connector processes this DwCA generated by 170.php:
https://editors.eol.org/eol_php_code/applications/content_server/resources/170.tar.gz
This connector then finally generates 170_final.tar.gz
Where all .mov files (from 170.tar.gz) are converted to .mp4 files.

This connector is for those partners who host movie (.mov) files.
Script should be able to:
- download .mov file
- convert to .mp4
- use editors.eol.org path in accessURI in DwCA

1. split:
$ tar cz 170 | split -b 300000000 - ./170.gz_
2. then download each file locally and merge:
$ cat 170.gz_* | tar xz

scp 170.gz_al archive:~/temp/mp4/.
scp 170.gz_ak archive:~/temp/mp4/.
scp 170.gz_aj archive:~/temp/mp4/.
scp 170.gz_ai archive:~/temp/mp4/.
scp 170.gz_ah archive:~/temp/mp4/.
scp 170.gz_ag archive:~/temp/mp4/.
scp 170.gz_af archive:~/temp/mp4/.
scp 170.gz_ae archive:~/temp/mp4/.
scp 170.gz_ad archive:~/temp/mp4/.
scp 170.gz_ac archive:~/temp/mp4/.
scp 170.gz_ab archive:~/temp/mp4/.
scp 170.gz_aa archive:~/temp/mp4/.

scp 170_final.tar.gz archive:~/temp/.

Statistics
http://rs.tdwg.org/dwc/terms/taxon: Total: 514
        http://purl.org/dc/dcmitype/StillImage: 1408
        http://purl.org/dc/dcmitype/MovingImage: 451
        http://creativecommons.org/licenses/by-nc-sa/3.0/: 1859
        image/jpeg: 1408
        video/mp4: 451
    Total: 1859

170_final	Thursday 2019-09-26 03:56:49 AM	{"media_resource.tab":1859,"taxon.tab":514}

*/

include_once(dirname(__FILE__) . "/../../config/environment.php");
// $GLOBALS['ENV_DEBUG'] = true;
// ini_set('memory_limit','8096M');
$timestart = time_elapsed();

/* Start 1st part -- download the .mov and convert to .mp4 locally
$resource_id = '170';
require_library('connectors/MovieFilesAPI');
$dwca_file = 'https://editors.eol.org/eol_php_code/applications/content_server/resources/170.tar.gz';
$func = new MovieFilesAPI(false, $resource_id, $dwca_file);
$func->download_mov_convert_2_mp4();
unset($func);
*/

// /* Start 2nd part -- create the DwCA 170_final.tar.gz
$resource_id = '170_final';
$dwca_file = 'https://editors.eol.org/eol_php_code/applications/content_server/resources/170.tar.gz';
process_resource_url($dwca_file, $resource_id);
// */

$elapsed_time_sec = time_elapsed() - $timestart;
echo "\n\n";
echo "elapsed time = " . $elapsed_time_sec/60 . " minutes \n";
echo "elapsed time = " . $elapsed_time_sec/60/60 . " hours \n";
echo "\nDone processing.\n";

function process_resource_url($dwca_file, $resource_id)
{
    require_library('connectors/DwCA_Utility');
    $func = new DwCA_Utility($resource_id, $dwca_file);

    /* Orig in meta.xml has capital letters. Just a note reminder. */

    $preferred_rowtypes = array('http://rs.tdwg.org/dwc/terms/taxon');
    /* This 1 will be processed in MovieFilesAPI.php which will be called from DwCA_Utility.php
    http://eol.org/schema/media/Document
    */
    $func->convert_archive($preferred_rowtypes);
    Functions::finalize_dwca_resource($resource_id, false, true);
}
?>