<?php
namespace php_active_record;
/* connector for Tucanes de Colombia
Partner provides DWC-A file generated by an IPT
estimated execution time:  2 seconds (just a sample of 20 taxa)
*/

include_once(dirname(__FILE__) . "/../../config/environment.php");
$timestart = time_elapsed();
require_library('connectors/INBioAPI');
require_library('connectors/TucanesAPI');
$resource_id = 349; 
$taxa = TucanesAPI::get_all_taxa($resource_id);
$xml = \SchemaDocument::get_taxon_xml($taxa);
$xml = INBioAPI::assign_eol_subjects($xml);
$resource_path = CONTENT_RESOURCE_LOCAL_PATH . $resource_id . ".xml";
$OUT = fopen($resource_path, "w");
fwrite($OUT, $xml);
fclose($OUT);

// set to force harvest
if(filesize(CONTENT_RESOURCE_LOCAL_PATH . $resource_id . ".xml") > 600)
{
    $GLOBALS['db_connection']->update("UPDATE resources SET resource_status_id=" . ResourceStatus::force_harvest()->id . " WHERE id=" . $resource_id);
}

$elapsed_time_sec = time_elapsed() - $timestart;
echo "\n";
echo "elapsed time = " . $elapsed_time_sec . " seconds   \n";
echo "elapsed time = " . $elapsed_time_sec/60 . " minutes   \n";
echo "\n\n Done processing.";
?>