<?php
namespace php_active_record;
/* From this adjustment request by Jen: https://eol-jira.bibalex.org/browse/DATA-1400?focusedCommentId=64344&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-64344

from legacy https://editors.eol.org/eol_php_code/applications/content_server/resources/707_24Oct2017.tar.gz

707	Tuesday 2017-10-24 11:11:52 AM	{"agents.txt":0,"associations.txt":0,"common names.txt":0,"events.txt":0,
                                     "measurements or facts.txt":4078,"media.txt":0,
                                     "occurrences.txt":632,"references.txt":0,
                                     "taxa.txt":632}
Statistics
    http://rs.tdwg.org/dwc/terms/taxon: Total: 632
    http://rs.tdwg.org/dwc/terms/measurementorfact: Total: 4078
        
*The legacy 707.tar.gz was renamed to 707_24Oct2017.tar.gz. We're going to use the latter moving forward.
This legacy DwCA was lastly generated by: spreadsheet_2_dwca.php _ 707. That was back in 24Oct2017.
-----------------------------------------------------------------------------------------------------------------------
started using 707.php - Jan, 2020
707	Tuesday 2020-01-28 08:46:58 AM	{"measurement_or_fact_specific.tab":4078,"occurrence_specific.tab":632,"taxon.tab":632,"time_elapsed":{"sec":34.47,"min":0.57,"hr":0.01}}
run once only, since it only adjusts a DwCA that is based on a one-time spreadsheet.
*/

include_once(dirname(__FILE__) . "/../../config/environment.php");
$timestart = time_elapsed();
$resource_id = 707;
$dwca_file = 'https://editors.eol.org/eol_php_code/applications/content_server/resources/707_24Oct2017.tar.gz';
process_resource_url($dwca_file, $resource_id, $timestart);

function process_resource_url($dwca_file, $resource_id, $timestart)
{
    require_library('connectors/DwCA_Utility');
    $func = new DwCA_Utility($resource_id, $dwca_file);

    /* Orig in meta.xml has capital letters. Just a note reminder. */
    $preferred_rowtypes = array('http://rs.tdwg.org/dwc/terms/taxon');
    /* This will be processed in BirdsADW_Data.php which will be called from DwCA_Utility.php
    http://rs.tdwg.org/dwc/terms/measurementorfact
    http://rs.tdwg.org/dwc/terms/occurrence
    */
    $func->convert_archive($preferred_rowtypes);
    Functions::finalize_dwca_resource($resource_id, false, true, $timestart);
}
?>