<?php
namespace php_active_record;
/* From this adjustment request by Jen: https://eol-jira.bibalex.org/browse/DATA-1814?focusedCommentId=63686&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-63686
Request is to remove all descendants of Aves (https://paleobiodb.org/classic/checkTaxonInfo?taxon_no=36616).
from the DwCA 368.tar.gz.

This script adjusts the 368.tar.gz generated by pbdb_fresh_harvest.php.
This script is run after pbdb_fresh_harvest.php.

368	Tuesday 2019-08-13 11:25:11 AM	                    {"measurement_or_fact_specific.tab":2276891,"occurrence.tab":515360,"taxon.tab":376240,"vernacular_name.tab":5863}
368_removed_aves	Wednesday 2019-10-02 06:07:17 AM	{"measurement_or_fact_specific.tab":2286206,"occurrence.tab":516498,"taxon.tab":378639,"vernacular_name.tab":4540}

V091905247994
V10190530133396
V1019053013339
V1019053013339

you can run immediately one after the other: Same in Jenkins in eol-archive:
php update_resources/connectors/pbdb_fresh_harvest.php
php update_resources/connectors/remove_Aves_children_from_368.php
php update_resources/connectors/synonyms_handling.php _ 368_final
*/

include_once(dirname(__FILE__) . "/../../config/environment.php");
ini_set('memory_limit','8096M');
$timestart = time_elapsed();
// $GLOBALS['ENV_DEBUG'] = true;
$resource_id = '368_removed_aves';
if(Functions::is_production()) $dwca_file = 'https://editors.eol.org/eol_php_code/applications/content_server/resources/368.tar.gz'; //the DwCA to adjust.
else                           $dwca_file = 'http://localhost/eol_php_code/applications/content_server/resources_2/368.tar.gz'; //during development only
process_resource_url($dwca_file, $resource_id);

$elapsed_time_sec = time_elapsed() - $timestart;
echo "\n\n";
echo "elapsed time = " . $elapsed_time_sec/60 . " minutes \n";
echo "elapsed time = " . $elapsed_time_sec/60/60 . " hours \n";
echo "\nDone processing.\n";

function process_resource_url($dwca_file, $resource_id)
{
    require_library('connectors/DwCA_Utility');
    $func = new DwCA_Utility($resource_id, $dwca_file);

    /* Orig in meta.xml has capital letters. Just a note reminder.
    rowType="http://rs.tdwg.org/dwc/terms/Taxon">
    rowType="http://rs.tdwg.org/dwc/terms/Occurrence">
    rowType="http://rs.tdwg.org/dwc/terms/MeasurementOrFact">
    rowType="http://rs.gbif.org/terms/1.0/VernacularName">
    */

    $preferred_rowtypes = array(); //no prefered. All will be customized
    $func->convert_archive($preferred_rowtypes);
    unset($func);
    Functions::finalize_dwca_resource($resource_id, false, true); //, true, true
}
?>