<?php
namespace php_active_record;
/* connector: [gbif_taxa] 
Based from: https://eol-jira.bibalex.org/browse/TRAM-552
This connector processes this file: eol_php_code/applications/genHigherClass/temp/GBIF_Taxa_accepted.tsv
Which was generated by this script: eol_php_code/applications/genHigherClass/generate_cmd.php
Uses GBIF API: http://www.gbif.org/developer/species
*/
class GBIFtaxaAPI
{
    function __construct()
    {
        // http://api.gbif.org/v1/species/8115426/children?offset=0
        $this->api['children'] = "http://api.gbif.org/v1/species/";
        
        $this->download_options = array(
            'cache_path'         => '/Volumes/Thunderbolt4/eol_cache_gbif/',
            'expire_seconds'     => false, //5184000, //2 months to expire; true expires now
            'download_wait_time' => 2000000, 'timeout' => 600, 'download_attempts' => 1, 'delay_in_minutes' => 1);
    }

    function prune_gbif_backbone_taxa($taxon_extension)
    {
        /* testing...
        // $children = self::get_all_children_of_taxon(212);
        // $children = self::get_all_children_of_taxon(1496);
        // $children = self::get_all_children_of_taxon(136);
        // $children = self::get_all_children_of_taxon(35);
        $children = self::get_all_children_of_taxon(7707728);
        
        print_r($children);
        echo "\ntotal = " . count($children) . "\n";
        exit("\n");
        */
        
        // self::get_ids_2prune_using_google_sheet();
        self::get_ids_2prune_using_tsv(); exit("\n");
        
        // normal operation
        // temp/GBIF_Taxa_accepted.tsv
        echo "\nsource: [$taxon_extension]\n";
        $filename = pathinfo($taxon_extension, PATHINFO_FILENAME);
        $new_file = str_replace($filename, $filename."_pruned", $taxon_extension);
        echo("\ntarget: [$new_file]\n");
        
        $fn = fopen($new_file, "w");
        $ids_2prune = self::get_ids_2prune_using_google_sheet();
        foreach(new FileIterator($taxon_extension) as $line_number => $line)
        {
            if($line)
            {
                $col = explode("\t", $line);
                $taxonID = $col[0];
                echo "\n[$taxonID]";
                if(!in_array($taxonID, $ids_2prune)) fwrite($fn, $line."\n");
            }
        }
        fclose($fn);
        return $new_file;
    }

    private function get_ids_2prune_using_google_sheet()
    {
        $final = array();
        $values = self::get_google_sheet();
        foreach($values as $row)
        {
            $taxonID = $row[0];
            echo "\nprocessing [$taxonID]\n";
            $children = self::get_all_children_of_taxon($taxonID);
            $children[] = $taxonID;
            $final = array_merge($final, $children);
            $final = array_unique($final);
        }
        $final = array_unique($final);
        return $final;
    }
    
    private function get_ids_2prune_using_tsv()
    {
        $final = array();
        $spreadsheet = "http://localhost/cp/GBIF/from_Google_spreadsheet/Branches to prune from GBIF - Sheet1.tsv";
        if($filename = Functions::save_remote_file_to_local($spreadsheet, $this->download_options)) {}
        $i = 0;
        $m = 1834; //total divided by 6
        foreach(new FileIterator($filename) as $line_number => $line)
        {
            $i++;
            // /* breakdown when caching:
            $cont = false;
            
            if($i >= 1    && $i < 25) $cont = true;
            // if($i >= 25    && $i < 50) $cont = true;
            // if($i >= 50    && $i < 100) $cont = true;
            // if($i >= 100    && $i < 200) $cont = true; done
            // if($i >= 200    && $i < 300) $cont = true;
            
            if(!$cont) continue;
            // */
            if($line)
            {
                $line = explode("\t", $line);
                if($i == 1) $fields = $line;
                else
                {
                    $taxonID = $line[0];
                    echo "\n".$taxonID." ";
                    // if($taxonID == 212) exit("\n$taxonID will start\n");
                    if(in_array($taxonID, array(7707728, 8,13,35,9,212,131,1496,789,1458,136,62)))
                    {
                        // exit("\n[$taxonID]\n");
                        continue;
                    }
                    
                    $children = self::get_all_children_of_taxon($taxonID);
                    $children[] = $taxonID;
                    $final = array_merge($final, $children);
                    $final = array_unique($final);
                }
            }
            // if($taxonID == 212) exit("\n$taxonID finished\n");
            
        }
        unlink($filename);
        $final = array_unique($final);
        return $final;
    }
    
    private function get_children($taxonID)
    {
        $final = array();
        $offset = 0;
        $limit = 100; //default is 20
        $continue = true;
        while($continue)
        {
            $url = $this->api['children'].$taxonID."/children?limit=$limit";
            if($offset) $url .= "&offset=$offset";
            if($json = Functions::lookup_with_cache($url, $this->download_options))
            {
                $j = json_decode($json);
                // print_r($j); exit;
                echo "\n [$url] incremental count: " . count($j->results) . "\n";
                foreach($j->results as $r) $final[] = str_ireplace("gbif:", "", $r->taxonID);
                if($j->endOfRecords) $continue = false;
            }
            else break; //just try again next time...
            $offset += $limit;
        }
        return $final;
    }
    
    private function get_all_children_of_taxon($taxon_id)
    {
        $taxo_tmp = array();
        //start ====
        $temp = self::get_children($taxon_id);
        $taxo_tmp = array_merge($taxo_tmp, $temp);

        //start 2nd loop -> process children of children
        foreach($temp as $id)
        {
            $temp2 = self::get_children($id);
            $taxo_tmp = array_merge($taxo_tmp, $temp2);
            //start 3rd loop -> process children of children of children
            foreach($temp2 as $id)
            {
                $temp3 = self::get_children($id);
                $taxo_tmp = array_merge($taxo_tmp, $temp3);
                //start 4th loop -> process children of children of children
                foreach($temp3 as $id)
                {
                    $temp4 = self::get_children($id);
                    $taxo_tmp = array_merge($taxo_tmp, $temp4);
                    //start 5th loop -> process children of children of children
                    foreach($temp4 as $id)
                    {
                        print("\nreaches 5th loop\n");
                        $temp5 = self::get_children($id);
                        $taxo_tmp = array_merge($taxo_tmp, $temp5);
                        //start 6th loop -> process children of children of children
                        foreach($temp5 as $id)
                        {
                            print("\nreaches 6th loop\n");
                            $temp6 = self::get_children($id);
                            $taxo_tmp = array_merge($taxo_tmp, $temp6);
                            //start 7th loop -> process children of children of children
                            foreach($temp6 as $id)
                            {
                                print("\nreaches 7th loop\n");
                                $temp7 = self::get_children($id);
                                $taxo_tmp = array_merge($taxo_tmp, $temp7);
                                //start 8th loop -> process children of children of children
                                foreach($temp7 as $id)
                                {
                                    $temp8 = self::get_children($id);
                                    $taxo_tmp = array_merge($taxo_tmp, $temp8);
                                    //start 9th loop -> process children of children of children
                                    foreach($temp8 as $id)
                                    {
                                        $temp9 = self::get_children($id);
                                        $taxo_tmp = array_merge($taxo_tmp, $temp9);
                                        //start 10th loop -> process children of children of children
                                        foreach($temp9 as $id)
                                        {
                                            $temp10 = self::get_children($id);
                                            $taxo_tmp = array_merge($taxo_tmp, $temp10);
                                            //start 11th loop -> process children of children of children
                                            foreach($temp10 as $id)
                                            {
                                                $temp11 = self::get_children($id);
                                                $taxo_tmp = array_merge($taxo_tmp, $temp11);
                                                //start 12th loop -> process children of children of children
                                                foreach($temp11 as $id)
                                                {
                                                    $temp12 = self::get_children($id);
                                                    $taxo_tmp = array_merge($taxo_tmp, $temp12);
                                                    //start 13th loop -> process children of children of children
                                                    foreach($temp12 as $id)
                                                    {
                                                        print("\nreaches 13th loop\n");
                                                        $temp13 = self::get_children($id);
                                                        $taxo_tmp = array_merge($taxo_tmp, $temp13);
                                                        //start 14th loop -> process children of children of children
                                                        foreach($temp13 as $id)
                                                        {
                                                            print("\nreaches 14th loop\n");
                                                            $temp14 = self::get_children($id);
                                                            $taxo_tmp = array_merge($taxo_tmp, $temp14);
                                                            //start 15th loop -> process children of children of children
                                                            foreach($temp14 as $id)
                                                            {
                                                                print("\nreaches 15th loop\n");
                                                                $temp15 = self::get_children($id);
                                                                $taxo_tmp = array_merge($taxo_tmp, $temp15);
                                                                //start 16th loop -> process children of children of children
                                                                foreach($temp15 as $id)
                                                                {
                                                                    print("\nreaches 16th loop\n");
                                                                    $temp16 = self::get_children($id);
                                                                    $taxo_tmp = array_merge($taxo_tmp, $temp16);
                                                                    //start 17th loop -> process children of children of children
                                                                    foreach($temp16 as $id)
                                                                    {
                                                                        print("\nreaches 17th loop\n");
                                                                        $temp17 = self::get_children($id);
                                                                        $taxo_tmp = array_merge($taxo_tmp, $temp17);
                                                                        //start 18th loop -> process children of children of children
                                                                        foreach($temp17 as $id)
                                                                        {
                                                                            exit("\nreaches 18th loop\n");
                                                                            $temp18 = self::get_children($id);
                                                                            $taxo_tmp = array_merge($taxo_tmp, $temp18);
                                                                        }
                                                                        //end 18th loop
                                                                    }
                                                                    //end 17th loop
                                                                }
                                                                //end 16th loop
                                                            }
                                                            //end 15th loop
                                                        }
                                                        //end 14th loop
                                                    }
                                                    //end 13th loop
                                                }
                                                //end 12th loop
                                            }
                                            //end 11th loop
                                        }
                                        //end 10th loop
                                    }
                                    //end 9th loop
                                }
                                //end 8th loop
                            }
                            //end 7th loop
                        }
                        //end 6th loop
                    }
                    //end 5th loop
                }
                //end 4th loop
            }
            //end 3rd loop
        }
        //end 2nd loop
        $taxo_tmp = array_unique($taxo_tmp);
        $taxo_tmp = array_filter($taxo_tmp);
        //end ====
        return $taxo_tmp;
    }

    private function get_google_sheet() //sheet found here: https://eol-jira.bibalex.org/browse/TRAM-552?focusedCommentId=61031&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-61031
    {
        require_library('connectors/GoogleClientAPI');
        $func = new GoogleClientAPI();
        $params['spreadsheetID'] = '1-nTN2i_epQzl-rOaQJjIFbVRUfVirVKZpTEwC8kH7k8';
        $params['range']         = 'Sheet1!A2:A'; //where "A" is the starting column, "C" is the ending column, and "2" is the starting row.
        return $func->access_google_sheet($params);
    }

}
?>
