<?php
namespace php_active_record;
include_once(dirname(__FILE__) . "/../../config/environment.php");
$browser = Functions::getBrowser(); // echo "Browser: " . $browser;
if($browser == 'Firefox') $browser_comment = "Browse...";
else                      $browser_comment = "Choose File"; //Safari Chrome etc
?>
<table border="1" cellpadding="15" cellspacing="1" align="center" width="40%">
    <tr align="center"><td><b>Taxonomic Validation Tool</b></td></tr>
    <tr>
        <td>
        <table><tr>
            <td width="70%">
                <font size="3">
                 <ul>
                  <li>Download to your computer the input spreadsheet template <a href="temp/Trait_template.xlsx">here</a>.</li>
                  <li>Open spreadsheet, enter your own data and save.</li>
                  <li>Upload file using [<?php echo $browser_comment ?>] button below.</li>
                </ul>
                </font>
            </td>
            <td>
                <form action="form_result_upload.php" method="post" enctype="multipart/form-data">
                <font size="2">
                    You can also upload an updated spreadsheet template, with an updated vocabulary sheet.<br>
                    Upload template: <input type="file" name="file_upload" id="file_upload" size="100"><br>
                        <input type="submit" value="Submit template">
                        <input type="reset" value="Reset">
                </font>
                </form>
            
            </td>
        </tr></table>
        </td>
    </tr>
    <form action="form_result.php" method="post" enctype="multipart/form-data">
    <tr>
        <td>
            <font size="3">Upload input Excel file: </font><input type="file" name="file_upload" id="file_upload" size="100">
        </td>
    </tr>
    <tr>
        <td>
            <small>(.xlsx or .xls) OR (.xlsx.zip, .xls.zip)</small>
        </td>
    </tr>
    <tr>
        <td>
            <table>
            <tr><td>Description:</td> <td><input type='text' name='Short_Desc' size='100' required></td></tr>
            <tr><td></td>
                <td>
                    <small>Please enter a short description of your file.
                    </small>
                </td>
            </tr>
            </table>
        </td>
    </tr>
    <tr>
        <td>
            <table>
            <tr><td>Upload ID:</td> <td><input type='text' name='Filename_ID'></td></tr>
            <tr><td></td>
                <td>
                    <small>Optional. Please enter Upload ID to update a previous upload.<br>
                    Upload ID is generated by the system.<br>
                    If left blank, the system assumes this will be a new upload and will create a new resource in OpenData.eol.org.
                    </small>
                </td>
            </tr>
            </table>
        </td>
    </tr>
    <tr align="center">
        <td>
            <input type="submit" value="Convert Spreadsheet to DwCA">
            <input type="reset" value="Reset">
        </td>
    </tr>
    </form>
    <tr align="left">
        <td><?php echo "<a href='https://opendata.eol.org/dataset/trait-spreadsheet-repository'>OpenData Resources For Uploaded Spreadsheets</a>"; ?>
         | <?php echo "<a href='../../../html/tools.html'>Tools</a>"; ?>
        </td>
    </tr>
</table>
