#!/bin/bash

chown nginx:nginx /data/www/eol_php_code/update_resources/*
chmod ug+x /data/www/eol_php_code/update_resources/*

chown nginx:nginx /data/www/eol_php_code/update_resources/connectors/*
chmod ug+x /data/www/eol_php_code/update_resources/connectors/*

chown nginx:nginx /data/www/eol_php_code/update_resources/connectors/helpers/*
chmod ug+x /data/www/eol_php_code/update_resources/connectors/helpers/*

chown nginx:nginx /data/www/eol_php_code/rake_tasks/*
chmod ug+x /data/www/eol_php_code/rake_tasks/*

chown nginx:nginx /data/www/resources/*
chmod ug+rw /data/www/resources/*

